version: "3"
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    volumes:
      - /opt/tsdb/influxdb2:/var/lib/influxdb2:Z
      - /opt/tsdb/influxcfg:/etc/influxdb2:Z
    ports:
      - 8088:8088
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: username
      DOCKER_INFLUXDB_INIT_PASSWORD: passwd
      DOCKER_INFLUXDB_INIT_ORG: my-org
      DOCKER_INFLUXDB_INIT_BUCKET: buketname
      # DOCKER_INFLUXDB_INIT_RETENTION: 720
#Didn't verify,just keep it as notes
